# Generated by Django 5.0 on 2023-12-18 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(choices=[('MCAS', 'MCAS'), ('CSOM', 'CSOM'), ('CSON', 'CSON'), ('LYNCH', 'LYNCH'), ('LAW', 'LAW'), ('WOODS', 'WOODS'), ('STM', 'STM'), ('SSW', 'SSW')], max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(blank=True, choices=[('student', 'Student'), ('admin', 'Admin')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(default='01/01/2023', max_length=255)),
                ('schedule', models.CharField(default='none', max_length=255)),
                ('instructor', models.CharField(default='none', max_length=255)),
                ('requisite', models.CharField(default='none', max_length=255)),
                ('department', models.CharField(default='none', max_length=255)),
                ('level', models.CharField(default='none', max_length=255)),
                ('courseIdentifier', models.CharField(default='none', max_length=255)),
                ('max_students_on_watch', models.IntegerField(default=0)),
                ('min_students_on_watch', models.IntegerField(default=0)),
                ('credits', models.CharField(default='3', max_length=10)),
                ('time_slots', models.CharField(default='', max_length=255)),
                ('days', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(default='', max_length=255, unique=True)),
                ('instructor', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('currentSeats', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('maxSeats', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('courseid', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('EagleVision.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('major_1', models.CharField(blank=True, choices=[('', 'Select a Major'), ('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('Applied Physics', 'Applied Physics'), ('Art History', 'Art History'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Classics', 'Classics'), ('Communication', 'Communication'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('English', 'English'), ('Environmental Geoscience', 'Environmental Geoscience'), ('Environmental Studies', 'Environmental Studies'), ('Film Studies', 'Film Studies'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German Studies', 'German Studies'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Human-Centered Engineering', 'Human-Centered Engineering'), ('Independent', 'Independent'), ('International Studies', 'International Studies'), ('Islamic Civilization and Societies', 'Islamic Civilization and Societies'), ('Italian', 'Italian'), ('Linguistics', 'Linguistics'), ('Mathematics', 'Mathematics'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Russian', 'Russian'), ('Slavic Studies', 'Slavic Studies'), ('Sociology', 'Sociology'), ('Studio Art', 'Studio Art'), ('Theatre', 'Theatre'), ('Theology', 'Theology'), ('American Heritage', 'American Heritage'), ('Applied Psychology & Human Development', 'Applied Psychology & Human Development'), ('Elementary Education', 'Elementary Education'), ('Perspectives on Spanish America', 'Perspectives on Spanish America'), ('Secondary Education', 'Secondary Education'), ('Transformative Educational Studies', 'Transformative Educational Studies'), ('Accounting', 'Accounting'), ('Accounting for Finance and Consulting', 'Accounting for Finance and Consulting'), ('Business Analytics', 'Business Analytics'), ('Entrepreneurship', 'Entrepreneurship'), ('Finance', 'Finance'), ('General Management', 'General Management'), ('Management and Leadership', 'Management and Leadership'), ('Marketing', 'Marketing'), ('Operations Management', 'Operations Management'), ('Global Public Health and the Common Good', 'Global Public Health and the Common Good'), ('Nursing', 'Nursing'), ('Applied Liberal Arts', 'Applied Liberal Arts'), ('Interdisciplinary Studies', 'Interdisciplinary Studies'), ('Sustainability', 'Sustainability'), ('Business', 'Business'), ('Criminal and SocialJustice', 'Criminal and Social Justice'), ('Cybersecurity', 'Cybersecurity'), ('Information Systems', 'Information Systems')], max_length=255, null=True)),
                ('major_2', models.CharField(blank=True, choices=[('', 'Select a Major'), ('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('Applied Physics', 'Applied Physics'), ('Art History', 'Art History'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Classics', 'Classics'), ('Communication', 'Communication'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('English', 'English'), ('Environmental Geoscience', 'Environmental Geoscience'), ('Environmental Studies', 'Environmental Studies'), ('Film Studies', 'Film Studies'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German Studies', 'German Studies'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Human-Centered Engineering', 'Human-Centered Engineering'), ('Independent', 'Independent'), ('International Studies', 'International Studies'), ('Islamic Civilization and Societies', 'Islamic Civilization and Societies'), ('Italian', 'Italian'), ('Linguistics', 'Linguistics'), ('Mathematics', 'Mathematics'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Russian', 'Russian'), ('Slavic Studies', 'Slavic Studies'), ('Sociology', 'Sociology'), ('Studio Art', 'Studio Art'), ('Theatre', 'Theatre'), ('Theology', 'Theology'), ('American Heritage', 'American Heritage'), ('Applied Psychology & Human Development', 'Applied Psychology & Human Development'), ('Elementary Education', 'Elementary Education'), ('Perspectives on Spanish America', 'Perspectives on Spanish America'), ('Secondary Education', 'Secondary Education'), ('Transformative Educational Studies', 'Transformative Educational Studies'), ('Accounting', 'Accounting'), ('Accounting for Finance and Consulting', 'Accounting for Finance and Consulting'), ('Business Analytics', 'Business Analytics'), ('Entrepreneurship', 'Entrepreneurship'), ('Finance', 'Finance'), ('General Management', 'General Management'), ('Management and Leadership', 'Management and Leadership'), ('Marketing', 'Marketing'), ('Operations Management', 'Operations Management'), ('Global Public Health and the Common Good', 'Global Public Health and the Common Good'), ('Nursing', 'Nursing'), ('Applied Liberal Arts', 'Applied Liberal Arts'), ('Interdisciplinary Studies', 'Interdisciplinary Studies'), ('Sustainability', 'Sustainability'), ('Business', 'Business'), ('Criminal and SocialJustice', 'Criminal and Social Justice'), ('Cybersecurity', 'Cybersecurity'), ('Information Systems', 'Information Systems')], max_length=255, null=True)),
                ('major_3', models.CharField(blank=True, choices=[('', 'Select a Major'), ('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('Applied Physics', 'Applied Physics'), ('Art History', 'Art History'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Classics', 'Classics'), ('Communication', 'Communication'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('English', 'English'), ('Environmental Geoscience', 'Environmental Geoscience'), ('Environmental Studies', 'Environmental Studies'), ('Film Studies', 'Film Studies'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German Studies', 'German Studies'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Human-Centered Engineering', 'Human-Centered Engineering'), ('Independent', 'Independent'), ('International Studies', 'International Studies'), ('Islamic Civilization and Societies', 'Islamic Civilization and Societies'), ('Italian', 'Italian'), ('Linguistics', 'Linguistics'), ('Mathematics', 'Mathematics'), ('Music', 'Music'), ('Neuroscience', 'Neuroscience'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Russian', 'Russian'), ('Slavic Studies', 'Slavic Studies'), ('Sociology', 'Sociology'), ('Studio Art', 'Studio Art'), ('Theatre', 'Theatre'), ('Theology', 'Theology'), ('American Heritage', 'American Heritage'), ('Applied Psychology & Human Development', 'Applied Psychology & Human Development'), ('Elementary Education', 'Elementary Education'), ('Perspectives on Spanish America', 'Perspectives on Spanish America'), ('Secondary Education', 'Secondary Education'), ('Transformative Educational Studies', 'Transformative Educational Studies'), ('Accounting', 'Accounting'), ('Accounting for Finance and Consulting', 'Accounting for Finance and Consulting'), ('Business Analytics', 'Business Analytics'), ('Entrepreneurship', 'Entrepreneurship'), ('Finance', 'Finance'), ('General Management', 'General Management'), ('Management and Leadership', 'Management and Leadership'), ('Marketing', 'Marketing'), ('Operations Management', 'Operations Management'), ('Global Public Health and the Common Good', 'Global Public Health and the Common Good'), ('Nursing', 'Nursing'), ('Applied Liberal Arts', 'Applied Liberal Arts'), ('Interdisciplinary Studies', 'Interdisciplinary Studies'), ('Sustainability', 'Sustainability'), ('Business', 'Business'), ('Criminal and SocialJustice', 'Criminal and Social Justice'), ('Cybersecurity', 'Cybersecurity'), ('Information Systems', 'Information Systems')], max_length=255, null=True)),
                ('minor_1', models.CharField(blank=True, choices=[('', 'Select a Minor'), ('Accounting for CPAs', 'Accounting for CPAs'), ('Accounting for Finance & Consulting', 'Accounting for Finance & Consulting'), ('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('American Studies', 'American Studies'), ('Ancient Civilization (Classics)', 'Ancient Civilization (Classics)'), ('Ancient Greek', 'Ancient Greek'), ('Applied Psychology & Human Development', 'Applied Psychology & Human Development'), ('Arabic Studies', 'Arabic Studies'), ('Art History', 'Art History'), ('Asian Studies', 'Asian Studies'), ('Biology', 'Biology'), ('Catholic Studies', 'Catholic Studies'), ('Chemistry', 'Chemistry'), ('Chinese', 'Chinese'), ('Communications', 'Communications'), ('Computer Science', 'Computer Science'), ('Cyberstrategy and Design', 'Cyberstrategy and Design'), ('Data Science', 'Data Science'), ('Design Thinking and Innovation', 'Design Thinking and Innovation'), ('East European Studies', 'East European Studies'), ('Economics', 'Economics'), ('Educational Theater', 'EducationalTheater'), ('English', 'English'), ('Environmental Studies', 'Environmental Studies'), ('Faith Peace & Justice', 'Faith Peace & Justice'), ('Film Studies', 'Film Studies'), ('Finance', 'Finance'), ('Foundations in Education', 'Foundations in Education'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German', 'German'), ('German Studies', 'German Studies'), ('Global Public Health and the Common Good', 'Global Public Health and the Common Good'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Immigration Education and Humanitarian Studies', 'Immigration, Education, and Humanitarian Studies'), ('Inclusive Education', 'Inclusive Education'), ('International Studies', 'International Studies'), ('Irish Studies', 'Irish Studies'), ('Islamic Civilization & Societies', 'Islamic Civilization & Societies'), ('Italian', 'Italian'), ('Jewish Studies', 'Jewish Studies'), ('Journalism', 'Journalism'), ('Latin', 'Latin'), ('Latin American Studies', 'Latin American Studies'), ('Leadership in Higher Education and Community Settings', 'Leadership in Higher Education and Community Settings'), ('Linguistics', 'Linguistics'), ('Management and Leadership', 'Management and Leadership'), ('Managing for Social Impact and Public Good', 'Managing for Social Impact and Public Good'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Medical Humanities, Health, and Culture', 'Medical Humanities, Health, and Culture'), ('Middle School Mathematics Teaching', 'Middle School Mathematics Teaching'), ('Music', 'Music'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Religion and Public Life', 'Religion and Public Life'), ('Research Evaluation and Measurement', 'Research, Evaluation, and Measurement'), ('Restorative and Transformational Justice', 'Restorative and Transformational Justice'), ('Russian', 'Russian'), ('Secondary Education', 'Secondary Education'), ('Sociology', 'Sociology'), ('Special Education', 'Special Education'), ('Studio Art', 'Studio Art'), ('TELL certificate', 'TELL certificate'), ('Theatre', 'Theatre'), ('Theology', 'Theology'), ('Womens & Gender Studies', 'Womens & Gender Studies')], max_length=255, null=True)),
                ('minor_2', models.CharField(blank=True, choices=[('', 'Select a Minor'), ('Accounting for CPAs', 'Accounting for CPAs'), ('Accounting for Finance & Consulting', 'Accounting for Finance & Consulting'), ('African and African Diaspora Studies', 'African and African Diaspora Studies'), ('American Studies', 'American Studies'), ('Ancient Civilization (Classics)', 'Ancient Civilization (Classics)'), ('Ancient Greek', 'Ancient Greek'), ('Applied Psychology & Human Development', 'Applied Psychology & Human Development'), ('Arabic Studies', 'Arabic Studies'), ('Art History', 'Art History'), ('Asian Studies', 'Asian Studies'), ('Biology', 'Biology'), ('Catholic Studies', 'Catholic Studies'), ('Chemistry', 'Chemistry'), ('Chinese', 'Chinese'), ('Communications', 'Communications'), ('Computer Science', 'Computer Science'), ('Cyberstrategy and Design', 'Cyberstrategy and Design'), ('Data Science', 'Data Science'), ('Design Thinking and Innovation', 'Design Thinking and Innovation'), ('East European Studies', 'East European Studies'), ('Economics', 'Economics'), ('Educational Theater', 'EducationalTheater'), ('English', 'English'), ('Environmental Studies', 'Environmental Studies'), ('Faith Peace & Justice', 'Faith Peace & Justice'), ('Film Studies', 'Film Studies'), ('Finance', 'Finance'), ('Foundations in Education', 'Foundations in Education'), ('French', 'French'), ('Geological Sciences', 'Geological Sciences'), ('German', 'German'), ('German Studies', 'German Studies'), ('Global Public Health and the Common Good', 'Global Public Health and the Common Good'), ('Hispanic Studies', 'Hispanic Studies'), ('History', 'History'), ('Immigration Education and Humanitarian Studies', 'Immigration, Education, and Humanitarian Studies'), ('Inclusive Education', 'Inclusive Education'), ('International Studies', 'International Studies'), ('Irish Studies', 'Irish Studies'), ('Islamic Civilization & Societies', 'Islamic Civilization & Societies'), ('Italian', 'Italian'), ('Jewish Studies', 'Jewish Studies'), ('Journalism', 'Journalism'), ('Latin', 'Latin'), ('Latin American Studies', 'Latin American Studies'), ('Leadership in Higher Education and Community Settings', 'Leadership in Higher Education and Community Settings'), ('Linguistics', 'Linguistics'), ('Management and Leadership', 'Management and Leadership'), ('Managing for Social Impact and Public Good', 'Managing for Social Impact and Public Good'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Medical Humanities, Health, and Culture', 'Medical Humanities, Health, and Culture'), ('Middle School Mathematics Teaching', 'Middle School Mathematics Teaching'), ('Music', 'Music'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Religion and Public Life', 'Religion and Public Life'), ('Research Evaluation and Measurement', 'Research, Evaluation, and Measurement'), ('Restorative and Transformational Justice', 'Restorative and Transformational Justice'), ('Russian', 'Russian'), ('Secondary Education', 'Secondary Education'), ('Sociology', 'Sociology'), ('Special Education', 'Special Education'), ('Studio Art', 'Studio Art'), ('TELL certificate', 'TELL certificate'), ('Theatre', 'Theatre'), ('Theology', 'Theology'), ('Womens & Gender Studies', 'Womens & Gender Studies')], max_length=255, null=True)),
                ('eagle_id', models.CharField(max_length=50, unique=True)),
                ('graduation_semester', models.CharField(choices=[('Spring 2024', 'Spring 2024'), ('Fall 2024', 'Fall 2024'), ('Spring 2025', 'Spring 2025'), ('Fall 2025', 'Fall 2025'), ('Spring 2026', 'Spring 2026'), ('Fall 2026', 'Fall 2026'), ('Spring 2027', 'Spring 2027'), ('Fall 2027', 'Fall 2027')], max_length=11)),
            ],
            options={
                'abstract': False,
            },
            bases=('EagleVision.person',),
        ),
        migrations.CreateModel(
            name='MostPopularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_popular_course', models.CharField(default='none', max_length=255)),
                ('most_popular_course_count', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EagleVision.systemsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EagleVision.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EagleVision.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
