# Generated by Django 4.2.6 on 2023-12-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EagleVision.section'),
            preserve_default=False,
        ),
    ]
