# Generated by Django 4.2.7 on 2023-12-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(choices=[('MCAS', 'MCAS'), ('CSOM', 'CSOM'), ('CSON', 'CSON'), ('LYNCH', 'LYNCH'), ('LAW', 'LAW'), ('WOODS', 'WOODS'), ('STM', 'STM'), ('SSW', 'SSW')], max_length=10),
        ),
    ]
