# Generated by Django 4.2.6 on 2023-12-04 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(default='01/01/2023', max_length=255)),
                ('schedule', models.CharField(default='none', max_length=255)),
                ('instructor', models.CharField(default='none', max_length=255)),
                ('requisite', models.CharField(default='none', max_length=255)),
                ('department', models.CharField(default='none', max_length=255)),
                ('courseIdentifier', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('currentSeats', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('maxSeats', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('courseid', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EagleVision.course')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'course')},
        ),
    ]
