# Generated by Django 4.2.6 on 2023-12-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='most_popular_courses',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='most_popular_couses_count',
            field=models.IntegerField(default=0),
        ),
    ]
