# Generated by Django 5.0 on 2023-12-05 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students_on_watch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='min_students_on_watch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EagleVision.section'),
            preserve_default=False,
        ),
    ]
