# Generated by Django 4.2.6 on 2023-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
