# Generated by Django 4.2.7 on 2023-12-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
    ]
