# Generated by Django 4.2.6 on 2023-12-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
