# Generated by Django 4.2.7 on 2023-11-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_joined',
        ),
    ]
