# Generated by Django 4.2 on 2023-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation_semester',
            field=models.CharField(choices=[('Spring2024', 'Spring 2024'), ('Fall2024', 'Fall 2024'), ('Spring2025', 'Spring 2025'), ('Fall2025', 'Fall 2025'), ('Spring2026', 'Spring 2026'), ('Fall2026', 'Fall 2026'), ('Spring2027', 'Spring 2027'), ('Fall2027', 'Fall 2027')], max_length=10),
        ),
    ]
