# Generated by Django 4.2.6 on 2023-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=255),
        ),
    ]
