# Generated by Django 4.2.6 on 2023-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0002_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='extra_info_filled_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_info_filled_out',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
