# Generated by Django 4.2.7 on 2023-12-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0002_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
