# Generated by Django 4.2.6 on 2023-12-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0002_alter_systemstate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
