# Generated by Django 4.2.6 on 2023-12-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0002_systemsnapshot_most_popular_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_popular_course', models.CharField(default='none', max_length=255)),
                ('most_popular_course_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='most_popular_courses',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='most_popular_couses_count',
        ),
    ]
