# Generated by Django 4.2.6 on 2023-12-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0003_alter_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_slots',
            field=models.CharField(default='', max_length=255),
        ),
    ]
