# Generated by Django 4.2.7 on 2023-12-05 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0003_section_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EagleVision.section'),
        ),
    ]
