# Generated by Django 4.2.6 on 2023-11-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0003_admin_extra_info_filled_out_person_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='extra_info_filled_out',
        ),
        migrations.RemoveField(
            model_name='student',
            name='extra_info_filled_out',
        ),
    ]
