# Generated by Django 4.2.6 on 2023-11-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0003_course'),
        ('EagleVision', '0004_remove_admin_extra_info_filled_out_and_more'),
    ]

    operations = [
    ]
