# Generated by Django 4.2.7 on 2023-11-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0007_alter_systemstate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='state',
            field=models.BooleanField(),
        ),
    ]
