# Generated by Django 4.2.7 on 2023-11-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0008_alter_systemstate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.CharField(default='01/01/2023', max_length=255),
        ),
    ]
