# Generated by Django 4.2.7 on 2023-11-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0009_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requisite',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
