# Generated by Django 4.2.7 on 2023-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0010_course_requisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
