# Generated by Django 4.2.6 on 2023-11-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0011_course_instructor_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
