# Generated by Django 4.2.6 on 2023-11-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0015_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course_id',
        ),
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
