# Generated by Django 4.2.6 on 2023-11-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0016_remove_section_course_id_section_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time_slot',
        ),
    ]
