# Generated by Django 4.2.6 on 2023-11-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0017_remove_course_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
