# Generated by Django 4.2.6 on 2023-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0018_remove_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='courseid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
