# Generated by Django 4.2.6 on 2023-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0020_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseIdentifier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
