# Generated by Django 4.2.6 on 2023-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0021_course_courseidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseIdentifier',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
