# Generated by Django 4.2.6 on 2023-12-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0022_alter_course_courseidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
