# Generated by Django 4.2.6 on 2023-12-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0023_systemsnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsnapshot',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='systemsnapshot',
            old_name='snapshot_name',
            new_name='name',
        ),
    ]
