# Generated by Django 4.2.6 on 2023-12-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0024_alter_course_major'),
        ('EagleVision', '0024_rename_timestamp_systemsnapshot_created_at_and_more'),
    ]

    operations = [
    ]
