# Generated by Django 4.2.6 on 2023-12-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EagleVision', '0025_merge_20231204_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
    ]
